In [2]:
from caffe2.python import core, workspace
import numpy as np 

In [3]:
X = np.random.rand(2, 5, 3).astype(np.float32) 

In [4]:
print(X)

[[[ 0.13253027  0.90434247  0.02526305]
  [ 0.67464566  0.38786858  0.42217353]
  [ 0.33778286  0.7821064   0.04334169]
  [ 0.88407576  0.42954266  0.68552959]
  [ 0.73543739  0.96087408  0.07003585]]

 [[ 0.55055773  0.86309969  0.04553951]
  [ 0.93194878  0.25179058  0.54651076]
  [ 0.59739774  0.72449315  0.72188663]
  [ 0.33392504  0.69899517  0.19179392]
  [ 0.59689021  0.52796525  0.96804172]]]


In [5]:
sqr_op = core.CreateOperator( "Sqr", ["X"],["Z"], name="sqr_op") 


In [6]:
print(str(sqr_op))

input: "X"
output: "Z"
name: "sqr_op"
type: "Sqr"



In [7]:
workspace.FeedBlob("sqr_data", X)

True

In [8]:
print("Blobs im Workspace {}".format(workspace.Blobs()))

Blobs im Workspace [u'sqr_data']


In [10]:
sqr_data = workspace.FetchBlob("sqr_data")

In [11]:
print("sqr_data:\n{}".format(sqr_data))

sqr_data:
[[[ 0.13253027  0.90434247  0.02526305]
  [ 0.67464566  0.38786858  0.42217353]
  [ 0.33778286  0.7821064   0.04334169]
  [ 0.88407576  0.42954266  0.68552959]
  [ 0.73543739  0.96087408  0.07003585]]

 [[ 0.55055773  0.86309969  0.04553951]
  [ 0.93194878  0.25179058  0.54651076]
  [ 0.59739774  0.72449315  0.72188663]
  [ 0.33392504  0.69899517  0.19179392]
  [ 0.59689021  0.52796525  0.96804172]]]
