In [1]:
from caffe2.python import core, workspace
import numpy as np 

In [2]:
X = np.random.rand(2, 5, 3).astype(np.float32) 

In [3]:
print(X)

[[[ 0.24687533  0.88691854  0.2724967 ]
  [ 0.63865823  0.84956026  0.06888136]
  [ 0.70406801  0.71547377  0.7400828 ]
  [ 0.91612256  0.69894713  0.47145969]
  [ 0.42497662  0.37014362  0.07496428]]

 [[ 0.60018927  0.46916196  0.03994764]
  [ 0.93692034  0.20711136  0.92701334]
  [ 0.50472409  0.54931086  0.97193342]
  [ 0.56057662  0.82151747  0.33385313]
  [ 0.65733653  0.63362354  0.11832458]]]


In [4]:
sqr_op = core.CreateOperator( "Sqr", ["X"],["Z"], name="sqr_op") 


In [5]:
print(str(sqr_op))

input: "X"
output: "Z"
name: "sqr_op"
type: "Sqr"



In [6]:
workspace.FeedBlob("X", X)

True

In [7]:
workspace.RunOperatorOnce(sqr_op)

True

In [8]:
print("Blobs im Workspace {}".format(workspace.Blobs()))

Blobs im Workspace [u'X', u'Z']


In [9]:
Z = workspace.FetchBlob("Z")

In [10]:
print("sqr_data:\n{}".format(Z))

sqr_data:
[[[ 0.06094743  0.78662449  0.07425445]
  [ 0.40788433  0.72175264  0.00474464]
  [ 0.49571174  0.51190269  0.54772258]
  [ 0.83928055  0.48852709  0.22227423]
  [ 0.18060513  0.1370063   0.00561964]]

 [[ 0.36022717  0.22011295  0.00159581]
  [ 0.87781972  0.04289512  0.85935372]
  [ 0.25474641  0.30174243  0.94465458]
  [ 0.31424615  0.67489094  0.11145791]
  [ 0.43209133  0.4014788   0.01400071]]]
