In [1]:
import tensorflow as tf

In [3]:
s = tf.InteractiveSession()

In [4]:
s1 = tf.linspace(1.0, 42.0, 4, name='biszweiundvierzig')

In [7]:
print(s1.eval())

[  1.          14.66666698  28.33333397  42.        ]


In [8]:
r1 = tf.range(start=0, delta=3, limit=23)

In [9]:
print(r1.eval())

[ 0  3  6  9 12 15 18 21]


In [10]:
c1 = tf.constant([ [1, 0], [0, 0], [0, 1], [1, 1]])
s2 = tf.random_shuffle(c1)

In [11]:
print(s2.eval())

[[0 1]
 [1 0]
 [1 1]
 [0 0]]


In [12]:
norm = tf.random_normal([3, 3], mean=1, stddev=42)

In [13]:
print(s.run(norm))

[[ 47.25289917  -9.8089695  -44.71429825]
 [ 13.36789322 -19.97893143 -29.65545654]
 [ -4.86712885 -15.18634033 -34.05137634]]


In [14]:
uni = tf.random_uniform([3, 3], minval=1, maxval=10, dtype=tf.int32)

In [16]:
print(s.run(uni))

[[6 4 1]
 [2 2 2]
 [8 6 4]]
